layout_spectrum: 0.8937606
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.8709924523718655
  brandStrength: 0.920742
  lightness: 0.8551814353559166
  brandColors:
    - '#88806E'
    - '#FBFCFC'
    - '#39312F'
    - '#1FA3E9'
    - '#E9635D'
  rhythmicContrast: 0.7827631204854697
typography_spectrum: 0.7078554641921073
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: CGN-MUSIC
