favicon: null
name: CGN-MUSIC
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8709924523718655
  brandStrength: 0.6749220855999738
  rhythmicContrast: 0.7827631204854697
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.8551814353559166
typography_spectrum: 0.7078554641921073
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8937606
analytics:
  twitter: null
  google: null
  facebook: null
